# Site settings
title: Cottleston Pie - A web design studio in Brooklyn New York
email: studio@havesomecottlestonpie.com
description: Cottleston Pie designs and builds websites for organizations making a positive impact in the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.havesomecottlestonpie.com" # the base hostname & protocol for your site
twitter_username: davedawson
github_username:  davedawson

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude: [node_modules, package.json, npm-debug.log, Gruntfile.js, scss]